### ISSUE TITLE
Visualization script will not run to completion

### ISSUE THREAD

**Issue by davidainman** [derpetermann/sBayes#23]
After the recent update, there is a problem when running the visualization script:

```
Traceback (most recent call last):
  File "/Users/david/opt/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/david/opt/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 1762, in <module>
    main()
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 1721, in main
    plot_map(plot, m)
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 1752, in plot_map
    iterate_or_run(
  File "/Users/david/Documents/sbayes/sbayes/cli.py", line 102, in iterate_or_run
    iterate_over_parameter(x, config_setter, function, print_message)
  File "/Users/david/Documents/sbayes/sbayes/cli.py", line 95, in iterate_over_parameter
    function(value)
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 1755, in <lambda>
    function=lambda x: plot.posterior_map(file_name=f'posterior_map_{m}_{x}')
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 912, in posterior_map
    self.visualize_base_map(extent, cfg_geo, cfg_graphic, ax)
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 802, in visualize_base_map
    self.add_background_map(cfg_geo, cfg_graphic, ax)
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 763, in add_background_map
    lon_0 = map_crs.coordinate_operation.params[0].value
AttributeError: 'NoneType' object has no attribute 'params'
```

I did some debugging and map_crs is appropriately set to EPSG:4326 (as per my config), but it looks like it has no dependent value coordinate_operation that the code is expecting. Something must have changed because this used to work.

**Comment by davidainman** [comment]
There is no shifting.
