### ISSUE TITLE
bbox is still being called in add_background_map

### ISSUE THREAD

**Issue by davidainman** [derpetermann/sBayes#25]
When running visualization the following error is encountered:

```
Traceback (most recent call last):
  File "/Users/david/opt/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/david/opt/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 1768, in <module>
    main()
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 1727, in main
    plot_map(plot, m)
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 1755, in plot_map
    plot.posterior_map(file_name='posterior_map_' + m)
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 941, in posterior_map
    self.add_overview_map(locations_map_crs, extent, cfg_geo, cfg_graphic, cfg_legend, ax)
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 716, in add_overview_map
    self.add_background_map(bbox, cfg_geo, cfg_graphic, axins)
TypeError: add_background_map() takes 3 positional arguments but 4 were given
```

"bbox" must be removed from that call.

**Comment by derpetermann** [comment]
fixed. please test
