### ISSUE TITLE
Configs in experiment (SA) not up to date

### ISSUE THREAD

**Issue by annagraff** [derpetermann/sBayes#28]
Running the SA experiment results in an error. The config.json file for this experiment does not seem to be up to date.
This is the error message:

(base) Administrators-MacBook-Pro:sBayes Anna$ python experiments/south_america/scripts/run_sa_exp.py
Fontconfig warning: ignoring UTF-8: not a valid region tag
Experiment: 2022-02-03_13-44
File location for results: None
Traceback (most recent call last):
  File "experiments/south_america/scripts/run_sa_exp.py", line 10, in <module>
    exp.load_config(config_file='experiments/south_america/config.json')
  File "/Users/anaconda3/lib/python3.8/site-packages/sbayes/experiment_setup.py", line 86, in load_config
    self.verify_config()
  File "/Users/anaconda3/lib/python3.8/site-packages/sbayes/experiment_setup.py", line 172, in verify_config
    raise NameError(f'{k} is not defined {self.config_file}')
NameError: n_areas is not defined /Users/Anna 1/sBayes/experiments/south_america/config.json

**Comment by derpetermann** [comment]
The SA configs are compatible with version 1.0
